# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NimbleSurvey' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NimbleSurvey
  pod 'SwiftKeychainWrapper'

  target 'NimbleSurveyTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
